#pragma once
#include <glad\glad.h>
#include <glfw3.h>
#include <iostream>
#include <vector>
#include <string>
#include <memory>
#include <unordered_map>
#include <functional>
#include <typeindex>
#include <type_traits>
#include <cassert>
#include <algorithm>
#include <chrono>
#include <queue>
#include <stack>
#include <sstream>
#include <iomanip>
#include <random>
#include <cmath>
#include <array>
#include <tuple>
#include <utility>
#include <bitset>
#include <Windows.h>